
import { TravelRequest, Project, CostCenter, TravelPolicy, SystemSettings, Agency, TravelerDetails, CompanyProfile } from '../types';
import { getSupabase } from './supabaseClient';

const STORAGE_KEY = 'cdg-travel-requests';
const SETTINGS_KEY = 'cdg-system-settings';

// Check Env Vars to set intelligent defaults
const ENV_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.REACT_APP_SUPABASE_URL || process.env.VITE_SUPABASE_URL || '';
const ENV_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.REACT_APP_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || '';

// Default Settings Structure
const DEFAULT_SETTINGS: SystemSettings = {
  featureMapping: {
      'CHAT': 'GEMINI',
      'OCR': 'GEMINI',
      'JUSTIFICATION': 'GEMINI',
      'POLICY': 'GEMINI',
      'DOC_GEN': 'MOCK'
  },
  latencySimulation: 500,
  apiConfigs: {
    gemini: {
      apiKey: process.env.API_KEY || '',
      model: 'gemini-3-flash-preview'
    },
    openai: { apiKey: '', model: 'gpt-4o' },
    custom: { endpoint: '', apiKey: '', model: '' }
  },
  databaseProvider: (ENV_URL && ENV_KEY) ? 'SUPABASE' : 'LOCAL_STORAGE', 
  databaseConfig: { 
      endpoint: '', 
      apiKey: '', 
      supabaseUrl: '', 
      supabaseKey: '' 
  },
  branding: {
      appName: 'CDG Travel Portal',
      primaryColor: '#0f172a', 
      sidebarColor: '#ffffff',
      logoUrl: ''
  },
  dashboardConfig: {
      showStats: true,
      showRecentRequests: true,
      showPendingApprovals: true,
      showCalendarWidget: false
  },
  docTemplates: {
      headerText: 'CDG Group - Internal Document',
      footerText: 'Generated by CDG Travel Portal',
      showLogo: true
  }
};

// --- INIT COMPANIES ---
const INIT_COMPANIES: CompanyProfile[] = [
    { id: 'CDG', name: 'Control Data (Thailand) Ltd' },
    { id: 'CDGS', name: 'CDG Systems Ltd' },
    { id: 'CDT', name: 'Computer Peripherals and Supplies Ltd' }
];

// --- INIT POLICY (Complex) ---
const INIT_POLICY: TravelPolicy = {
    companies: INIT_COMPANIES,
    
    // Simple defaults
    defaultHotelLimit: { domestic: 2000, international: 5000 },
    mileageRate: 5,

    // NEW: Complex Matrix Rules
    complexRules: [
        // CDG: Grade 13+ can fly Business if > 6 hours
        {
            id: 'R1', companyId: 'CDG', category: 'FLIGHT_CLASS',
            minJobGrade: 13, minDurationHours: 6, travelType: 'INTERNATIONAL',
            allowedValue: 'Business'
        },
        // CDG: Everyone else Economy
        {
            id: 'R2', companyId: 'CDG', category: 'FLIGHT_CLASS',
            minJobGrade: 0, maxJobGrade: 12, travelType: 'ALL',
            allowedValue: 'Economy'
        },
        // CDGS: Special Hotel Limit
        {
            id: 'R3', companyId: 'CDGS', category: 'HOTEL_LIMIT',
            travelType: 'DOMESTIC', allowedValue: 1500, currency: 'THB'
        }
    ],

    // NEW: DOA Matrix
    doaMatrix: [
        // CDG Rules
        {
            id: 'D1', companyId: 'CDG', priority: 1,
            minCost: 0, maxCost: 50000, travelType: 'ALL',
            approverChain: ['Line Manager']
        },
        {
            id: 'D2', companyId: 'CDG', priority: 2,
            minCost: 50001, maxCost: 200000, travelType: 'ALL',
            approverChain: ['Line Manager', 'Department Head']
        },
        {
            id: 'D3', companyId: 'CDG', priority: 3,
            minCost: 200001, maxCost: -1, travelType: 'ALL',
            approverChain: ['Line Manager', 'Department Head', 'CFO']
        },
        
        // CDGS Rules (Different Thresholds)
        {
            id: 'D4', companyId: 'CDGS', priority: 1,
            minCost: 0, maxCost: 30000, travelType: 'ALL',
            approverChain: ['Line Manager']
        },
        {
            id: 'D5', companyId: 'CDGS', priority: 2,
            minCost: 30001, maxCost: -1, travelType: 'ALL',
            approverChain: ['Line Manager', 'GM']
        }
    ]
};

// --- STATIC REFERENCE DATA (For Initialization Only) ---
const INIT_EMPLOYEES: TravelerDetails[] = [
    { id: 'EMP001', name: 'Alex Bennett', email: 'alex.b@cdg.co.th', department: 'Sales', companyId: 'CDG', position: 'Manager', jobGrade: 13, mobile: '081-111-2222', type: 'Employee', title: 'Mr.' },
    { id: 'EMP002', name: 'Sarah Connor', email: 'sarah.c@cdg.co.th', department: 'IT', companyId: 'CDGS', position: 'Staff', jobGrade: 10, mobile: '089-999-8888', type: 'Employee', title: 'Ms.' },
    { id: 'ADS001', name: 'Admin Support', email: 'admin@cdg.co.th', department: 'Admin', companyId: 'CDG', position: 'Staff', jobGrade: 9, mobile: '02-111-2222', type: 'Employee', title: 'Ms.' },
    { id: 'MGR001', name: 'John Manager', email: 'manager@cdg.co.th', department: 'Management', companyId: 'CDG', position: 'GM', jobGrade: 15, mobile: '081-999-9999', type: 'Employee', title: 'Mr.' },
    { id: 'PRE001', name: 'David President', email: 'president@cdg.co.th', department: 'Executive', companyId: 'CDG', position: 'President', jobGrade: 20, mobile: '081-999-0000', type: 'Employee', title: 'Mr.' },
    { id: 'IT001', name: 'Tech Admin', email: 'it.admin@cdg.co.th', department: 'IT', companyId: 'CDG', position: 'Admin', jobGrade: 12, mobile: '02-000-0000', type: 'Employee', title: 'Mr.' }
];

const INIT_PROJECTS: Project[] = [
    { code: 'PRJ-2024-001', name: 'Cloud Migration', manager: 'Alex Bennett', budget: 1000000, spent: 250000, status: 'Active' },
    { code: 'PRJ-2024-002', name: 'AI Integration', manager: 'Sarah Connor', budget: 500000, spent: 10000, status: 'Active' },
    { code: 'PRJ-2024-003', name: 'Infra Upgrade', manager: 'John Doe', budget: 2000000, spent: 1500000, status: 'Active' }
];

const INIT_COST_CENTERS: CostCenter[] = [
    { code: 'CC-GEN-001', name: 'General Mgmt', department: 'Management', budget: 5000000, available: 4500000 },
    { code: 'CC-SAL-002', name: 'Sales & Marketing', department: 'Sales', budget: 2000000, available: 1200000 },
    { code: 'CC-IT-003', name: 'IT Infrastructure', department: 'IT', budget: 3000000, available: 200000 }
];

const STATIC_AIRPORTS = [
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok' },
  { code: 'DMK', name: 'Don Mueang Intl', city: 'Bangkok' },
  { code: 'CNX', name: 'Chiang Mai Intl', city: 'Chiang Mai' },
  { code: 'HKT', name: 'Phuket Intl', city: 'Phuket' },
  { code: 'HDY', name: 'Hat Yai Intl', city: 'Hat Yai' },
  { code: 'SIN', name: 'Changi Airport', city: 'Singapore' },
  { code: 'NRT', name: 'Narita Intl', city: 'Tokyo' },
  { code: 'HND', name: 'Haneda Intl', city: 'Tokyo' },
  { code: 'LHR', name: 'Heathrow', city: 'London' },
  { code: 'JFK', name: 'John F. Kennedy', city: 'New York' },
  { code: 'SFO', name: 'San Francisco Intl', city: 'San Francisco' },
];

const STATIC_CITIES = [
  "Bangkok", "Chiang Mai", "Phuket", "Khon Kaen", "Pattaya", "Hat Yai",
  "Singapore", "Tokyo", "London", "New York", "San Francisco", 
  "Seoul", "Hong Kong", "Sydney", "Paris", "Berlin", "Vientiane", "Hanoi"
];

const STATIC_AIRLINES = [
  "Thai Airways", "Bangkok Airways", "AirAsia", "Nok Air", 
  "Singapore Airlines", "Japan Airlines", "ANA", "Emirates", "Qatar Airways"
];

// Helper to safely read localStorage
const safeGetItem = (key: string, defaultVal: any) => {
    try {
        const item = localStorage.getItem(key);
        return item ? JSON.parse(item) : defaultVal;
    } catch (e) {
        console.error(`Error reading ${key} from localStorage`, e);
        return defaultVal;
    }
};

export const storageService = {
  // --- System Settings ---
  getSettings: (): SystemSettings => {
    const loaded = safeGetItem(SETTINGS_KEY, DEFAULT_SETTINGS);
    // Merge defaults for new fields if they don't exist in stored version
    return { ...DEFAULT_SETTINGS, ...loaded, branding: { ...DEFAULT_SETTINGS.branding, ...loaded.branding }, dashboardConfig: { ...DEFAULT_SETTINGS.dashboardConfig, ...loaded.dashboardConfig } };
  },

  saveSettings: (settings: SystemSettings): void => {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
  },

  // --- Requests (CRUD) ---
  getRequests: async (): Promise<TravelRequest[]> => {
    const settings = storageService.getSettings();
    
    if (settings.databaseProvider === 'SUPABASE') {
        const sb = getSupabase();
        if (sb) {
            try {
                const { data, error } = await sb.from('travel_requests').select('*').order('created_at', { ascending: false });
                if (!error && data) {
                    return data.map((row: any) => ({
                        ...row.request_data, 
                        id: row.id,
                        status: row.status, 
                        requesterId: row.user_id, 
                        submittedAt: row.created_at
                    }));
                }
            } catch (e) { console.warn("Supabase fetch failed"); }
        }
    }
    return safeGetItem(STORAGE_KEY, []);
  },

  generateNextRequestId: async (): Promise<string> => {
    const requests = await storageService.getRequests();
    const currentYear = new Date().getFullYear();
    const prefix = `CDG${currentYear}`;
    const currentYearRequests = requests.filter(r => r.id && r.id.startsWith(prefix));
    
    if (currentYearRequests.length === 0) return `${prefix}0001`;

    let maxSeq = 0;
    currentYearRequests.forEach(r => {
        const numericPart = r.id.replace(prefix, '');
        const seq = parseInt(numericPart, 10);
        if (!isNaN(seq) && seq > maxSeq) maxSeq = seq;
    });

    return `${prefix}${(maxSeq + 1).toString().padStart(4, '0')}`;
  },

  saveRequest: async (request: TravelRequest): Promise<TravelRequest[]> => {
    const settings = storageService.getSettings();

    if (settings.databaseProvider === 'SUPABASE') {
        const sb = getSupabase();
        if (sb) {
            try {
                const payload = {
                    id: request.id,
                    user_id: request.requesterId,
                    status: request.status,
                    request_data: request,
                    updated_at: new Date().toISOString()
                };
                await sb.from('travel_requests').upsert(payload);
            } catch (e) { console.error("Cloud save failed", e); }
        }
    }

    const requests = await storageService.getRequests(); 
    const existingIndex = requests.findIndex(r => r.id === request.id);
    let newRequests;
    if (existingIndex >= 0) {
      newRequests = [...requests];
      newRequests[existingIndex] = request;
    } else {
      newRequests = [request, ...requests];
    }
    
    localStorage.setItem(STORAGE_KEY, JSON.stringify(newRequests));
    return newRequests; 
  },

  deleteRequest: async (id: string): Promise<TravelRequest[]> => {
    const settings = storageService.getSettings();

    if (settings.databaseProvider === 'SUPABASE') {
        const sb = getSupabase();
        if (sb) await sb.from('travel_requests').delete().eq('id', id);
    }

    const requests = safeGetItem(STORAGE_KEY, []);
    const newRequests = requests.filter((r: TravelRequest) => r.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(newRequests));
    return newRequests;
  },

  // --- Dynamic Master Data ---

  getEmployees: async (): Promise<TravelerDetails[]> => {
      const stored = safeGetItem('cdg-master-employees', null);
      if (stored) return stored;
      localStorage.setItem('cdg-master-employees', JSON.stringify(INIT_EMPLOYEES));
      return INIT_EMPLOYEES;
  },

  saveEmployees: async (employees: TravelerDetails[]): Promise<void> => {
      localStorage.setItem('cdg-master-employees', JSON.stringify(employees));
  },

  getProjects: async (): Promise<Project[]> => {
    const stored = safeGetItem('cdg-master-projects', null);
    if (stored) return stored;
    localStorage.setItem('cdg-master-projects', JSON.stringify(INIT_PROJECTS));
    return INIT_PROJECTS;
  },

  saveProjects: async (projects: Project[]): Promise<void> => {
      localStorage.setItem('cdg-master-projects', JSON.stringify(projects));
  },

  getCostCenters: async (): Promise<CostCenter[]> => {
    const stored = safeGetItem('cdg-master-costcenters', null);
    if (stored) return stored;
    localStorage.setItem('cdg-master-costcenters', JSON.stringify(INIT_COST_CENTERS));
    return INIT_COST_CENTERS;
  },

  saveCostCenters: async (costCenters: CostCenter[]): Promise<void> => {
      localStorage.setItem('cdg-master-costcenters', JSON.stringify(costCenters));
  },

  // --- Static Reference Data ---
  getAirports: async (): Promise<any[]> => STATIC_AIRPORTS,
  getCities: async (): Promise<string[]> => STATIC_CITIES,
  getAirlines: async (): Promise<string[]> => STATIC_AIRLINES,

  // --- Agencies ---
  getAgencies: async (): Promise<Agency[]> => {
     return safeGetItem('cdg-master-agencies', []);
  },

  saveAgencies: async (agencies: Agency[]): Promise<void> => {
      localStorage.setItem('cdg-master-agencies', JSON.stringify(agencies));
  },

  // --- Policy ---
  getPolicies: async (): Promise<TravelPolicy> => {
    // Attempt to load policy; if new fields (complexRules) don't exist, merge with INIT
    const loaded = safeGetItem('cdg-travel-policy', INIT_POLICY);
    if (!loaded.complexRules || !loaded.doaMatrix || !loaded.companies) {
        return { ...INIT_POLICY, ...loaded, complexRules: INIT_POLICY.complexRules, doaMatrix: INIT_POLICY.doaMatrix, companies: INIT_POLICY.companies };
    }
    return loaded;
  },

  savePolicies: async (policy: TravelPolicy): Promise<void> => {
    localStorage.setItem('cdg-travel-policy', JSON.stringify(policy));
  },
};
